version: '3'
services:
  swagger:
    build: .
    ports:
      - 10010:10010
    volumes:
      - .:/usr/src/app/swagger:delegated
      - /usr/src/app/swagger/node_modules
    stdin_open: true
    tty: true
    command: swagger project start
