swagger: "2.0"
info:
  version: "0.0.1"
  title: Simple Post App
host: localhost:10010
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /posts:
    get:
      parameters:
        - name: page
          in: query
          type: integer
          format: int64
        - name: limit
          in: query
          type: integer
          format: int64
      responses:
        "200":
          schema:
            $ref: "#/definitions/PostListModel"
          description: '' # これないとエラー
    post:
      parameters:
      - name: body
        in: body
        required: true
        schema:
          "$ref": "#/definitions/PostForCreateModel"
      responses:
        '200':
          schema:
            "$ref": "#/definitions/PostModel"
          description: '' # これないとエラー
    x-swagger-router-controller: dummy # これないとエラー
  /posts/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true # これないとエラー
        type: integer
        format: int64
      responses:
        '200':
          schema:
            "$ref": "#/definitions/PostModel"
          description: '' # これないとエラー
    patch:
      parameters:
      - name: id
        in: path
        required: true # これないとエラー
        type: integer
        format: int64
      - name: body
        in: body
        schema:
          "$ref": "#/definitions/PostForUpdateModel"
      responses:
        '200':
          schema:
            "$ref": "#/definitions/PostModel"
          description: '' # これないとエラー
    delete:
      parameters:
      - name: id
        in: path
        required: true # これないとエラー
        type: integer
        format: int64
      responses:
        '200':
          schema:
            "$ref": "#/definitions/OkModel"
          description: '' # これないとエラー
    x-swagger-router-controller: dummy # これないとエラー
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  OkModel:
    type: object
    properties:
      status:
        type: string
        enum:
        - ok
  PostForUpdateModel:
    type: object
    properties:
      title:
        type: string
      body:
        type: string
  PostForCreateModel:
    type: object
    properties:
      title:
        type: string
      body:
        type: string
  PostModel:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      body:
        type: string
  PostListModel:
    allOf:
    - "$ref": "#/definitions/ListBaseModel"
    - type: object
      properties:
        list:
          type: array
          items:
            "$ref": "#/definitions/PostModel"
  ListBaseModel:
    type: object
    properties:
      count:
        type: integer
        format: int64
      list:
        type: array
        items:
          type: object
